// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gmafffff.training.hotel.infrastructure.data.Sessions;

#nullable disable

namespace gmafffff.training.hotel.infrastructure.data.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20250628231418_AddRoomUniqueKey")]
    partial class AddRoomUniqueKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.AccommodationReport<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("AccommodationReportId");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DepartureDate")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Visitors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("RoomDetails", "gmafffff.training.hotel.domain.Model.AccommodationReport<System.Guid>.RoomDetails#RoomDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("Capacity")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TariffDetails", "gmafffff.training.hotel.domain.Model.AccommodationReport<System.Guid>.TariffDetails#TariffDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("Id");

                    b.ToTable("AccommodationReports");
                });

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.HotelBlock<int, System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("HotelBlockId");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.Person<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PersonId");

                    b.ComplexProperty<Dictionary<string, object>>("FullName", "gmafffff.training.hotel.domain.Model.Person<System.Guid>.FullName#PersonFullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Patronymic")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SurName")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("History", "gmafffff.training.hotel.domain.Model.Person<System.Guid>.History#VisitorHistory", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Count")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Duration")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.Room<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomId");

                    b.Property<int>("HotelBlockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HotelBlockId");

                    b.ComplexProperty<Dictionary<string, object>>("RoomDetails", "gmafffff.training.hotel.domain.Model.Room<System.Guid>.RoomDetails#RoomDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("Capacity")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("HotelBlockId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.RoomCleaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoomCleaningId");

                    b.Property<DateTime?>("CleaningCompleted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClean")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("CleaningCompleted IS NOT NULL");

                    b.Property<DateTime>("PutInLine")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomCleanings");
                });

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TariffId");

                    b.Property<int>("HotelBlockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HotelBlockId");

                    b.ComplexProperty<Dictionary<string, object>>("TariffDetails", "gmafffff.training.hotel.domain.Model.Tariff.TariffDetails#TariffDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("Id");

                    b.HasIndex("HotelBlockId");

                    b.ToTable("Tariff");
                });

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.Room<System.Guid>", b =>
                {
                    b.HasOne("gmafffff.training.hotel.domain.Model.HotelBlock<int, System.Guid>", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("gmafffff.training.hotel.domain.Model.RoomVisit<System.Guid>", "Visit", b1 =>
                        {
                            b1.Property<int>("RoomId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RoomId");

                            b1.Property<DateOnly>("ArrivalDate")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly?>("DepartureDatePlanned")
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("Visitors")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("rowVersion")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0);

                            b1.HasKey("RoomId");

                            b1.ToTable("RoomVisit", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoomId");

                            b1.OwnsOne("gmafffff.training.hotel.domain.Model.TariffDetails", "TariffDetails", b2 =>
                                {
                                    b2.Property<int>("RoomVisitRoomId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<double>("Value")
                                        .HasColumnType("REAL");

                                    b2.HasKey("RoomVisitRoomId");

                                    b2.ToTable("RoomVisit");

                                    b2.WithOwner()
                                        .HasForeignKey("RoomVisitRoomId");
                                });

                            b1.Navigation("TariffDetails")
                                .IsRequired();
                        });

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.RoomCleaning", b =>
                {
                    b.HasOne("gmafffff.training.hotel.domain.Model.Room<System.Guid>", "Room")
                        .WithMany("RoomCleanings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.Tariff", b =>
                {
                    b.HasOne("gmafffff.training.hotel.domain.Model.HotelBlock<int, System.Guid>", null)
                        .WithMany("Tariffs")
                        .HasForeignKey("HotelBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.HotelBlock<int, System.Guid>", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Tariffs");
                });

            modelBuilder.Entity("gmafffff.training.hotel.domain.Model.Room<System.Guid>", b =>
                {
                    b.Navigation("RoomCleanings");
                });
#pragma warning restore 612, 618
        }
    }
}
