<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0"/>
        <PackageReference Include="Light.GuardClauses" Version="12.0.0"/>
        <PackageReference Include="ZiggyCreatures.FusionCache" Version="2.3.0"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="LanguageExt.Core" Version="5.0.0-beta-46"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Mapster" Version="7.4.2-pre02"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0"/>
        <PackageReference Include="Scrutor" Version="6.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Validot" Version="2.5.0"/>
    </ItemGroup>

</Project>
